# -*- mode: org -*-
# -*- coding: utf-8 -*-
#+TITLE: tbot-800.ex
#+AUTHOR: Jongbin Oh
#+EMAIL: ohyecloudy@gmail.com

인용구를 일정 주기로 트위하는 봇. [[https://twitter.com/book_quote_bot][@book_quote_bot]], [[https://twitter.com/bquote_bot][@bquote_bot]] 계정에서 사용하고 있다.

** :rocket: 시작하기 (Getting Started)

   두 과정을 거쳐서 인용구를 트윗한다

*** 인용구 빌드

    인용구를 바로 트윗할 수 있게 가공하는 작업이 필요하다.

    #+begin_src elixir
      [
        %{
          quotations: [
            "독일에서 히틀러가 저지른 일들도 모두 합법적이었다는 것을 잊지 말라. - 마틴 루터 킹 %{버밍햄 감옥에서의 편지},",
          ]
        },
        %{
          origin: "케빈 켈리의 68가지 조언 https://news.hada.io/topic?id=2060",
          quotations: [
            "항상 데드라인을 요구하세요. 데드라인은 관계없거나 평범한 것들을 제거합니다. 데드라인이 '완벽하게' 만들지 못하게 방해해주니까, '다르게' 만들어야 합니다. 다른 것이 좋습니다.",
          ]
        }
      ]
    #+end_src

    이런 식으로 인용구 소스를 적는다. 출처가 있으면 =origin= 키 값을 사용하고 없다면 비워두면 된다.

    인용구 소스를 작성했다면 인용구를 빌드한다.

    #+begin_example
      script/quote-build q-src.exs\
          ohyecloudy\
          http://ohrepos.github.io/quotes-repo/quotes/\
          tweet_items.exs\
          quotes
    #+end_example

    인자는 다음과 같다.

    1. =q-src.exs= 인용구 파일 이름
    2. 트위터 계정 이름
       - 긴 인용구는 전체를 트윗할 수 없어서 html 페이지 링크를 단다. html 페이지에 기록하는 참고용 트위터 계정 이름이다
    3. html을 호스팅할 base url
       - 긴 트윗을 자르고 전체 인용구를 볼 수 있는 html 링크를 첨부하는데, 그때 사용한다
    4. 트윗 글자 수 규제를 지켜서 자른 문자열 리스트
    5. html 파일들을 저장할 디렉터리


    GitHub Actions로 인용구를 빌드하고 커밋하는 [[https://github.com/ohrepos/quotes-repo/blob/master/.github/workflows/elixir.yaml][ohrepos/quotes-repo]], [[https://github.com/ohrepos/pquotes-repo/blob/master/.github/workflows/elixir.yaml][ohrepos/pquotes-repo]] 저장소를 참고한다.

*** 일정 주기로 트윗

    #+begin_example
      $ export ACCOUNT1_INTERVAL_MINUTE=60
      $ export ACCOUNT1_KEY=[TWITTER_API_KEY]
      $ export ACCOUNT1_SECRET=[TWITTER_API_SECRET_KEY]
      $ export ACCOUNT1_TOKEN=[TWITTER_ACCESS_TOKEN]
      $ export ACCOUNT1_TOKEN_SECRET=[TWITTER_ACCESS_SECRET]
      $ export ACCOUNT1_TWEET_ITEMS_URL=[빌드한 인용구 url]
      $ export ACCOUNT2_INTERVAL_MINUTE=60
      $ export ACCOUNT2_KEY=[TWITTER_API_KEY]
      $ export ACCOUNT2_SECRET=[TWITTER_API_SECRET_KEY]
      $ export ACCOUNT2_TOKEN=[TWITTER_ACCESS_TOKEN]
      $ export ACCOUNT2_TOKEN_SECRET=[TWITTER_ACCESS_SECRET]
      $ export ACCOUNT2_TWEET_ITEMS_URL=[빌드한 인용구 url]
      $ export SENTRY_DSN=[SENTRY_DSN]
      $ script/server
    #+end_example

    트위터 계정을 여러개 지원한다. 에러 트래킹 툴로 [[https://sentry.io/welcome/?utm_source=google&utm_medium=cpc&utm_id=%7Bcampaignid_Google_Search_Brand_ROW_Alpha%7D&utm_content=g&utm_term=sentry&gad=1][sentry]]를 사용한다면 =SENTRY_DSN= 환경 변수를 세팅한다.

    참고로 빌드한 인용구는 url만 지원한다. 읽은 인용구를 다 트윗하면 인용구를 다시 읽는데, 이때 인용구 url로부터 다시 인용구를 읽어 온다. 인용구 빌드와 트위터 봇 실행 수명을 편하게 분리시키려고 url로부터 읽는 기능만 구현했다. 즉, 새로운 인용구가 추가돼서 새로 인용구가 빌드된다면 현재 실행중인 트위터 봇이 이전에 읽은 인용구를 다 트윗하고 난 후 자동으로 새롭게 추가된 인용구를 읽어서 트윗한다.

** :white_check_mark: 테스트 실행하기 (Running the tests)

   #+begin_example
     $ script/test
   #+end_example

** :balance_scale: 라이선스 (License)

   MIT 라이선스를 따르고 있습니다. =LICENSE= 파일을 참고하세요.

