#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
# https://raw.githubusercontent.com/github/scripts-to-rule-them-all/master/script/setup

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> App is now ready to go!"
